#Configuration of the token exchange service
#Properties here are especially used for issueing tokens
serviceConfiguration:
  #Token Exchange Issuer name (used as "iss" claim in issued tokens)
  issuer: <path:factory-x-ci-cd/data/blueprint-leo#token-exchange-url>
  #Choose filter manager by subject token (value: true) or actor token (value: false)
  chooseFilterManagerBySubjectToken: true
  #Alias of the signing key which is used as key-id in the issued tokens
  signingKeyAlias: demo-key
  tokenExchangeFilterConfigurationYml: filter-config/filter-config.yml
  plainkey:
    keyLocation: signingkey/private_key.pem
    keyId: demo-key
  outgoingTokenScopeClaimName: scope
  forceOverwriteIssuerWithConfiguredValue: false
  forceOverwriteIatWithNow: false
  forceNewJti: false
issuerSpecificConfiguration:
  - issuer: <path:factory-x-ci-cd/data/blueprint-leo#token-exchange-keycloak-issuer>
    jwksValue: |
      <path:factory-x-ci-cd/data/blueprint-leo#token-exchange-keycloak-jwks>
    connectionTimeoutInMs: 20000
    readTimeoutInMs: 20000
    tokenScopeClaimName: scope
    propagateIssuerToValidators: true
    disableSubjectTokenClaimsSetValidator: false
    subjectTokenClaimsSetValidator:
      issuerRequired: true
      requiredScopes:
        - <path:factory-x-ci-cd/data/blueprint-leo#token-exchange-scope-exchange>
      requiredAudiences:
        - <path:factory-x-ci-cd/data/blueprint-leo#token-exchange-scope-audience>
      expiryClaimRequired: true
      expiryCheckDisabled: false
      nbfClaimRequired: false
      nbfCheckDisabled: false
      iatClaimRequired: false
      iatCheckDisabled: false
    actorTokenRequired: false
    actorTokenClaimsSetValidator:
      issuerRequired: true
      requiredScopes:
        - <path:factory-x-ci-cd/data/blueprint-leo#token-exchange-scope-authentication>
      requiredAudiences:
        - <path:factory-x-ci-cd/data/blueprint-leo#token-exchange-scope-token>
