apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mxport-leo-token-exchange.fullname" . }}-ghcr
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "<path:factory-x-ci-cd/data/blueprint-leo#ghcr-username>",
          "password": "<path:factory-x-ci-cd/data/blueprint-leo#ghcr-token>"
        }
      }
    }
