apiVersion: v1
kind: Service
metadata:
  name: {{ include "mxport-leo-token-exchange.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
  selector:
    app: {{ include "mxport-leo-token-exchange.fullname" . }}
