# Copyright 2026 Factory-X Consortia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.rabbitmq.ingress.certManager.enabled }}
{{- $host := index (index .Values.rabbitmq.ingress.extraTls 0).hosts 0 }}
{{- $secretName := (index .Values.rabbitmq.ingress.extraTls 0).secretName }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-rabbitmq-mqtt
  labels:
    app.kubernetes.io/name: rabbitmq-mqtt
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.rabbitmq.ingress.certManager.clusterIssuer | default "letsencrypt-prod" }}
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: {{ .Release.Name }}-rabbitmq-mqtt
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ $host }}
      secretName: {{ $secretName }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /mqtt
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-rabbitmq-mqtt
                port:
                  number: 443
{{- end }}