apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sts-chart.fullname" . }}
  labels:
    {{- include "sts-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sts-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/server-config: {{ include (print $.Template.BasePath "/server-configmap.yaml") . | sha256sum }}
        checksum/filter-config: {{ include (print $.Template.BasePath "/filter-configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sts-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sts-chart.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_TOKEN_EXCHANGE_CONFIG_LOCATION
              value: {{ .Values.environment.springTokenExchangeConfigLocation | quote }}
            - name: SERVER_CONTEXT_PATH
              value: {{ .Values.environment.serverContextPath | quote }}
            - name: SERVER_PORT
              value: {{ .Values.service.port | quote }}
            - name: TRUSTED_LIST_ENABLE
              value: {{ .Values.trustlist.enabled | quote }}
            - name: TRUSTED_LIST_LOCATION
              value: {{ .Values.trustlist.location | quote }}
            - name: TRUSTED_LIST_SCHEMA
              value: {{ .Values.trustlist.schema | quote }}
            - name: TRUSTED_LIST_PUBLIC_KEY
              value: {{ .Values.trustlist.publicKey | quote }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: server-config
              mountPath: /app/server-config
              readOnly: true
            - name: filter-config
              mountPath: /app/filter-config
              readOnly: true
            - name: signingkey
              mountPath: /app/signingkey
              readOnly: true
            {{- if .Values.trustlist.enabled }}
            - name: trusted-list
              mountPath: /app/trusted-list
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: server-config
          configMap:
            name: {{ include "sts-chart.fullname" . }}-server-config
        - name: filter-config
          configMap:
            name: {{ include "sts-chart.fullname" . }}-filter-config
        - name: signingkey
          secret:
            secretName: {{ include "sts-chart.fullname" . }}-signingkey
        {{- if .Values.trustlist.enabled }}
        - name: trusted-list
          configMap:
            name: {{ include "sts-chart.fullname" . }}-trusted-list
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}