apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sts-chart.fullname" . }}-filter-config
data:
  filter-config.yml: |-
{{- $filter_count := len .Values.filterConfig }}
{{- range $i, $filter := .Values.filterConfig }}
    !!{{ $filter.filterType }}
      issuer: {{ $filter.issuer }}
      {{- if hasKey $filter "audience" }}
      audience: {{ $filter.audience }}
      {{- end}}
{{ toYaml $filter.parameters | indent 6}}
    {{- if ne (add $i 1) $filter_count}}
    ---
    {{- end}}
{{- end}}
