apiVersion: v1
kind: Service
metadata:
  name: {{ include (printf "%s.fullname" .Chart.Name) . }}
  labels:
    app.kubernetes.io/name: {{ include (printf "%s.name" .Chart.Name) . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ (index .Values.endpoints 0).port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include (printf "%s.name" .Chart.Name) . }}
    app.kubernetes.io/instance: {{ .Release.Name }}