# SPDX-License-Identifier: MIT
# Copyright (c) 2025 XITASO GmbH
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mnestix-tokenexchange-basyx-auth.appSecretName" . }}
  labels:
    {{- include "mnestix-tokenexchange-basyx-auth.labels" (dict "root" . "component" "shared") | nindent 4 }}
type: Opaque
stringData:
  backendApiKey: {{ .Values.secrets.backendApiKey | quote }}
  nextAuthSecret: {{ .Values.secrets.nextAuthSecret | quote }}
  secretEncKey: {{ .Values.secrets.secretEncKey | quote }}
  keycloakAdminUser: {{ .Values.keycloak.auth.adminUser | quote }}
  keycloakAdminPassword: {{ .Values.keycloak.auth.adminPassword | quote }}
  mongodbRootUsername: {{ .Values.mongodb.auth.rootUsername | quote }}
  mongodbRootPassword: {{ .Values.mongodb.auth.rootPassword | quote }}
{{- if and .Values.keycloak.enabled .Values.keycloak.tlsSecret.create }}
---
{{ $crt := .Values.keycloak.tlsSecret.crt | default (.Files.Get .Values.keycloak.tlsSecret.crtFile) }}
{{ $key := .Values.keycloak.tlsSecret.key | default (.Files.Get .Values.keycloak.tlsSecret.keyFile) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mnestix-tokenexchange-basyx-auth.keycloakTlsSecretName" . }}
  labels:
    {{- include "mnestix-tokenexchange-basyx-auth.labels" (dict "root" . "component" "keycloak") | nindent 4 }}
type: Opaque
stringData:
  server.crt: |
{{ $crt | nindent 4 }}
  server.key: |
{{ $key | nindent 4 }}
{{- end }}
{{- if and .Values.keycloak.enabled .Values.keycloak.realm.createConfigMap }}
---
{{ $realm := .Values.keycloak.realm.content | default (.Files.Get .Values.keycloak.realm.sourceFile) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mnestix-tokenexchange-basyx-auth.keycloakRealmConfigMapName" . }}
  labels:
    {{- include "mnestix-tokenexchange-basyx-auth.labels" (dict "root" . "component" "keycloak") | nindent 4 }}
data:
  {{ .Values.keycloak.realm.fileName }}: |
{{ $realm | nindent 4 }}
{{- end }}
