# Copyright 2026 Codewerk GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

worker_processes 1;
events { worker_connections 1024; }

http {
  error_log /usr/local/openresty/nginx/logs/error.log info;

  # Shared cache for exchanged tokens (10 MB)
  lua_shared_dict sts_token_cache 10m;

  # Set TLS certificates
  lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
  lua_ssl_verify_depth 3;

  resolver 8.8.8.8 valid=30s ipv6=off;

  server {
    listen 80;
    server_name <path:factory-x-ci-cd/data/gateway-sts-provider#gateway-host>;
    location = /healthz { return 200 "OK\n"; }

    location / {
      access_by_lua_block {
        require("sts").exchange({
          sts_url        = "https://<path:factory-x-ci-cd/data/gateway-sts-provider#sts-host>/sts/token",
          target_service = "provider-aas-environment",
        })
      }

      proxy_pass https://<path:factory-x-ci-cd/data/gateway-sts-provider#basyx-env-url>;
    }
  }
}