apiVersion: v1
kind: Secret
metadata:
  name: basyx-leo-step3-provider-ghcr-pull-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <path:factory-x-ci-cd/data/gateway-sts-provider#dockerconfigjson>
